# Generated by Django 5.2.4 on 2025-07-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
