# Generated by Django 5.2.4 on 2025-07-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tiitle',
            new_name='title',
        ),
    ]
